//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  portfolio: Portfolio;
  portfolioConnection: PortfolioConnection;
  tools: Tools;
  toolsConnection: ToolsConnection;
  warehouse: Warehouse;
  warehouseConnection: WarehouseConnection;
  notes: Notes;
  notesConnection: NotesConnection;
  about: About;
  aboutConnection: AboutConnection;
  site_config: Site_Config;
  site_configConnection: Site_ConfigConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPortfolioArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPortfolioConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PortfolioFilter>;
};


export type QueryToolsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryToolsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ToolsFilter>;
};


export type QueryWarehouseArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryWarehouseConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WarehouseFilter>;
};


export type QueryNotesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNotesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NotesFilter>;
};


export type QueryAboutArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
};


export type QuerySite_ConfigArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySite_ConfigConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Site_ConfigFilter>;
};

export type DocumentFilter = {
  portfolio?: InputMaybe<PortfolioFilter>;
  tools?: InputMaybe<ToolsFilter>;
  warehouse?: InputMaybe<WarehouseFilter>;
  notes?: InputMaybe<NotesFilter>;
  about?: InputMaybe<AboutFilter>;
  site_config?: InputMaybe<Site_ConfigFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Portfolio | Tools | Warehouse | Notes | About | Site_Config | Folder;

export type Portfolio = Node & Document & {
  __typename?: 'Portfolio';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  thumbnail?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PortfolioFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  date?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PortfolioConnectionEdges = {
  __typename?: 'PortfolioConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Portfolio>;
};

export type PortfolioConnection = Connection & {
  __typename?: 'PortfolioConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PortfolioConnectionEdges>>>;
};

export type Tools = Node & Document & {
  __typename?: 'Tools';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  thumbnail?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ToolsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  date?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ToolsConnectionEdges = {
  __typename?: 'ToolsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Tools>;
};

export type ToolsConnection = Connection & {
  __typename?: 'ToolsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ToolsConnectionEdges>>>;
};

export type Warehouse = Node & Document & {
  __typename?: 'Warehouse';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  thumbnail?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type WarehouseFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  thumbnail?: InputMaybe<ImageFilter>;
  date?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type WarehouseConnectionEdges = {
  __typename?: 'WarehouseConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Warehouse>;
};

export type WarehouseConnection = Connection & {
  __typename?: 'WarehouseConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<WarehouseConnectionEdges>>>;
};

export type Notes = Node & Document & {
  __typename?: 'Notes';
  title: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NotesFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type NotesConnectionEdges = {
  __typename?: 'NotesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Notes>;
};

export type NotesConnection = Connection & {
  __typename?: 'NotesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NotesConnectionEdges>>>;
};

export type About = Node & Document & {
  __typename?: 'About';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AboutFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type AboutConnectionEdges = {
  __typename?: 'AboutConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About>;
};

export type AboutConnection = Connection & {
  __typename?: 'AboutConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutConnectionEdges>>>;
};

export type Site_ConfigNavigation = {
  __typename?: 'Site_configNavigation';
  name?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
};

export type Site_ConfigFriendLinks = {
  __typename?: 'Site_configFriendLinks';
  name?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type Site_Config = Node & Document & {
  __typename?: 'Site_config';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  keywords?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  logo?: Maybe<Scalars['String']['output']>;
  siteName?: Maybe<Scalars['String']['output']>;
  copyright?: Maybe<Scalars['String']['output']>;
  navigation?: Maybe<Array<Maybe<Site_ConfigNavigation>>>;
  friendLinks?: Maybe<Array<Maybe<Site_ConfigFriendLinks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Site_ConfigNavigationFilter = {
  name?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type Site_ConfigFriendLinksFilter = {
  name?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type Site_ConfigFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  keywords?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  logo?: InputMaybe<StringFilter>;
  siteName?: InputMaybe<StringFilter>;
  copyright?: InputMaybe<StringFilter>;
  navigation?: InputMaybe<Site_ConfigNavigationFilter>;
  friendLinks?: InputMaybe<Site_ConfigFriendLinksFilter>;
};

export type Site_ConfigConnectionEdges = {
  __typename?: 'Site_configConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Site_Config>;
};

export type Site_ConfigConnection = Connection & {
  __typename?: 'Site_configConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Site_ConfigConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePortfolio: Portfolio;
  createPortfolio: Portfolio;
  updateTools: Tools;
  createTools: Tools;
  updateWarehouse: Warehouse;
  createWarehouse: Warehouse;
  updateNotes: Notes;
  createNotes: Notes;
  updateAbout: About;
  createAbout: About;
  updateSite_config: Site_Config;
  createSite_config: Site_Config;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePortfolioArgs = {
  relativePath: Scalars['String']['input'];
  params: PortfolioMutation;
};


export type MutationCreatePortfolioArgs = {
  relativePath: Scalars['String']['input'];
  params: PortfolioMutation;
};


export type MutationUpdateToolsArgs = {
  relativePath: Scalars['String']['input'];
  params: ToolsMutation;
};


export type MutationCreateToolsArgs = {
  relativePath: Scalars['String']['input'];
  params: ToolsMutation;
};


export type MutationUpdateWarehouseArgs = {
  relativePath: Scalars['String']['input'];
  params: WarehouseMutation;
};


export type MutationCreateWarehouseArgs = {
  relativePath: Scalars['String']['input'];
  params: WarehouseMutation;
};


export type MutationUpdateNotesArgs = {
  relativePath: Scalars['String']['input'];
  params: NotesMutation;
};


export type MutationCreateNotesArgs = {
  relativePath: Scalars['String']['input'];
  params: NotesMutation;
};


export type MutationUpdateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationCreateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationUpdateSite_ConfigArgs = {
  relativePath: Scalars['String']['input'];
  params: Site_ConfigMutation;
};


export type MutationCreateSite_ConfigArgs = {
  relativePath: Scalars['String']['input'];
  params: Site_ConfigMutation;
};

export type DocumentUpdateMutation = {
  portfolio?: InputMaybe<PortfolioMutation>;
  tools?: InputMaybe<ToolsMutation>;
  warehouse?: InputMaybe<WarehouseMutation>;
  notes?: InputMaybe<NotesMutation>;
  about?: InputMaybe<AboutMutation>;
  site_config?: InputMaybe<Site_ConfigMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  portfolio?: InputMaybe<PortfolioMutation>;
  tools?: InputMaybe<ToolsMutation>;
  warehouse?: InputMaybe<WarehouseMutation>;
  notes?: InputMaybe<NotesMutation>;
  about?: InputMaybe<AboutMutation>;
  site_config?: InputMaybe<Site_ConfigMutation>;
};

export type PortfolioMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  thumbnail?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ToolsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  thumbnail?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type WarehouseMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  thumbnail?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type NotesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type AboutMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type Site_ConfigNavigationMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type Site_ConfigFriendLinksMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type Site_ConfigMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  keywords?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
  siteName?: InputMaybe<Scalars['String']['input']>;
  copyright?: InputMaybe<Scalars['String']['input']>;
  navigation?: InputMaybe<Array<InputMaybe<Site_ConfigNavigationMutation>>>;
  friendLinks?: InputMaybe<Array<InputMaybe<Site_ConfigFriendLinksMutation>>>;
};

export type PortfolioPartsFragment = { __typename: 'Portfolio', title: string, description?: string | null, thumbnail?: string | null, date?: string | null, body?: any | null };

export type ToolsPartsFragment = { __typename: 'Tools', title: string, description?: string | null, thumbnail?: string | null, date?: string | null, body?: any | null };

export type WarehousePartsFragment = { __typename: 'Warehouse', title: string, description?: string | null, thumbnail?: string | null, date?: string | null, body?: any | null };

export type NotesPartsFragment = { __typename: 'Notes', title: string, body?: any | null };

export type AboutPartsFragment = { __typename: 'About', title: string, description?: string | null, date?: string | null, body?: any | null };

export type Site_ConfigPartsFragment = { __typename: 'Site_config', title: string, subtitle?: string | null, keywords?: string | null, description?: string | null, logo?: string | null, siteName?: string | null, copyright?: string | null, navigation?: Array<{ __typename: 'Site_configNavigation', name?: string | null, url?: string | null } | null> | null, friendLinks?: Array<{ __typename: 'Site_configFriendLinks', name?: string | null, url?: string | null, description?: string | null } | null> | null };

export type PortfolioQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PortfolioQuery = { __typename?: 'Query', portfolio: { __typename: 'Portfolio', id: string, title: string, description?: string | null, thumbnail?: string | null, date?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PortfolioConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PortfolioFilter>;
}>;


export type PortfolioConnectionQuery = { __typename?: 'Query', portfolioConnection: { __typename?: 'PortfolioConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PortfolioConnectionEdges', cursor: string, node?: { __typename: 'Portfolio', id: string, title: string, description?: string | null, thumbnail?: string | null, date?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ToolsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ToolsQuery = { __typename?: 'Query', tools: { __typename: 'Tools', id: string, title: string, description?: string | null, thumbnail?: string | null, date?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ToolsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ToolsFilter>;
}>;


export type ToolsConnectionQuery = { __typename?: 'Query', toolsConnection: { __typename?: 'ToolsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ToolsConnectionEdges', cursor: string, node?: { __typename: 'Tools', id: string, title: string, description?: string | null, thumbnail?: string | null, date?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type WarehouseQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type WarehouseQuery = { __typename?: 'Query', warehouse: { __typename: 'Warehouse', id: string, title: string, description?: string | null, thumbnail?: string | null, date?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type WarehouseConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WarehouseFilter>;
}>;


export type WarehouseConnectionQuery = { __typename?: 'Query', warehouseConnection: { __typename?: 'WarehouseConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'WarehouseConnectionEdges', cursor: string, node?: { __typename: 'Warehouse', id: string, title: string, description?: string | null, thumbnail?: string | null, date?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type NotesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NotesQuery = { __typename?: 'Query', notes: { __typename: 'Notes', id: string, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type NotesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NotesFilter>;
}>;


export type NotesConnectionQuery = { __typename?: 'Query', notesConnection: { __typename?: 'NotesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NotesConnectionEdges', cursor: string, node?: { __typename: 'Notes', id: string, title: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type AboutQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutQuery = { __typename?: 'Query', about: { __typename: 'About', id: string, title: string, description?: string | null, date?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AboutConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
}>;


export type AboutConnectionQuery = { __typename?: 'Query', aboutConnection: { __typename?: 'AboutConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutConnectionEdges', cursor: string, node?: { __typename: 'About', id: string, title: string, description?: string | null, date?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type Site_ConfigQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Site_ConfigQuery = { __typename?: 'Query', site_config: { __typename: 'Site_config', id: string, title: string, subtitle?: string | null, keywords?: string | null, description?: string | null, logo?: string | null, siteName?: string | null, copyright?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, navigation?: Array<{ __typename: 'Site_configNavigation', name?: string | null, url?: string | null } | null> | null, friendLinks?: Array<{ __typename: 'Site_configFriendLinks', name?: string | null, url?: string | null, description?: string | null } | null> | null } };

export type Site_ConfigConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Site_ConfigFilter>;
}>;


export type Site_ConfigConnectionQuery = { __typename?: 'Query', site_configConnection: { __typename?: 'Site_configConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Site_configConnectionEdges', cursor: string, node?: { __typename: 'Site_config', id: string, title: string, subtitle?: string | null, keywords?: string | null, description?: string | null, logo?: string | null, siteName?: string | null, copyright?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, navigation?: Array<{ __typename: 'Site_configNavigation', name?: string | null, url?: string | null } | null> | null, friendLinks?: Array<{ __typename: 'Site_configFriendLinks', name?: string | null, url?: string | null, description?: string | null } | null> | null } | null } | null> | null } };

export const PortfolioPartsFragmentDoc = gql`
    fragment PortfolioParts on Portfolio {
  __typename
  title
  description
  thumbnail
  date
  body
}
    `;
export const ToolsPartsFragmentDoc = gql`
    fragment ToolsParts on Tools {
  __typename
  title
  description
  thumbnail
  date
  body
}
    `;
export const WarehousePartsFragmentDoc = gql`
    fragment WarehouseParts on Warehouse {
  __typename
  title
  description
  thumbnail
  date
  body
}
    `;
export const NotesPartsFragmentDoc = gql`
    fragment NotesParts on Notes {
  __typename
  title
  body
}
    `;
export const AboutPartsFragmentDoc = gql`
    fragment AboutParts on About {
  __typename
  title
  description
  date
  body
}
    `;
export const Site_ConfigPartsFragmentDoc = gql`
    fragment Site_configParts on Site_config {
  __typename
  title
  subtitle
  keywords
  description
  logo
  siteName
  copyright
  navigation {
    __typename
    name
    url
  }
  friendLinks {
    __typename
    name
    url
    description
  }
}
    `;
export const PortfolioDocument = gql`
    query portfolio($relativePath: String!) {
  portfolio(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PortfolioParts
  }
}
    ${PortfolioPartsFragmentDoc}`;
export const PortfolioConnectionDocument = gql`
    query portfolioConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PortfolioFilter) {
  portfolioConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PortfolioParts
      }
    }
  }
}
    ${PortfolioPartsFragmentDoc}`;
export const ToolsDocument = gql`
    query tools($relativePath: String!) {
  tools(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ToolsParts
  }
}
    ${ToolsPartsFragmentDoc}`;
export const ToolsConnectionDocument = gql`
    query toolsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ToolsFilter) {
  toolsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ToolsParts
      }
    }
  }
}
    ${ToolsPartsFragmentDoc}`;
export const WarehouseDocument = gql`
    query warehouse($relativePath: String!) {
  warehouse(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...WarehouseParts
  }
}
    ${WarehousePartsFragmentDoc}`;
export const WarehouseConnectionDocument = gql`
    query warehouseConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: WarehouseFilter) {
  warehouseConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...WarehouseParts
      }
    }
  }
}
    ${WarehousePartsFragmentDoc}`;
export const NotesDocument = gql`
    query notes($relativePath: String!) {
  notes(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NotesParts
  }
}
    ${NotesPartsFragmentDoc}`;
export const NotesConnectionDocument = gql`
    query notesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NotesFilter) {
  notesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NotesParts
      }
    }
  }
}
    ${NotesPartsFragmentDoc}`;
export const AboutDocument = gql`
    query about($relativePath: String!) {
  about(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutParts
  }
}
    ${AboutPartsFragmentDoc}`;
export const AboutConnectionDocument = gql`
    query aboutConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutFilter) {
  aboutConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutParts
      }
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export const Site_ConfigDocument = gql`
    query site_config($relativePath: String!) {
  site_config(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Site_configParts
  }
}
    ${Site_ConfigPartsFragmentDoc}`;
export const Site_ConfigConnectionDocument = gql`
    query site_configConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Site_configFilter) {
  site_configConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Site_configParts
      }
    }
  }
}
    ${Site_ConfigPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      portfolio(variables: PortfolioQueryVariables, options?: C): Promise<{data: PortfolioQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioQueryVariables, query: string}> {
        return requester<{data: PortfolioQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioQueryVariables, query: string}, PortfolioQueryVariables>(PortfolioDocument, variables, options);
      },
    portfolioConnection(variables?: PortfolioConnectionQueryVariables, options?: C): Promise<{data: PortfolioConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioConnectionQueryVariables, query: string}> {
        return requester<{data: PortfolioConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioConnectionQueryVariables, query: string}, PortfolioConnectionQueryVariables>(PortfolioConnectionDocument, variables, options);
      },
    tools(variables: ToolsQueryVariables, options?: C): Promise<{data: ToolsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ToolsQueryVariables, query: string}> {
        return requester<{data: ToolsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ToolsQueryVariables, query: string}, ToolsQueryVariables>(ToolsDocument, variables, options);
      },
    toolsConnection(variables?: ToolsConnectionQueryVariables, options?: C): Promise<{data: ToolsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ToolsConnectionQueryVariables, query: string}> {
        return requester<{data: ToolsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ToolsConnectionQueryVariables, query: string}, ToolsConnectionQueryVariables>(ToolsConnectionDocument, variables, options);
      },
    warehouse(variables: WarehouseQueryVariables, options?: C): Promise<{data: WarehouseQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WarehouseQueryVariables, query: string}> {
        return requester<{data: WarehouseQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WarehouseQueryVariables, query: string}, WarehouseQueryVariables>(WarehouseDocument, variables, options);
      },
    warehouseConnection(variables?: WarehouseConnectionQueryVariables, options?: C): Promise<{data: WarehouseConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WarehouseConnectionQueryVariables, query: string}> {
        return requester<{data: WarehouseConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WarehouseConnectionQueryVariables, query: string}, WarehouseConnectionQueryVariables>(WarehouseConnectionDocument, variables, options);
      },
    notes(variables: NotesQueryVariables, options?: C): Promise<{data: NotesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NotesQueryVariables, query: string}> {
        return requester<{data: NotesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NotesQueryVariables, query: string}, NotesQueryVariables>(NotesDocument, variables, options);
      },
    notesConnection(variables?: NotesConnectionQueryVariables, options?: C): Promise<{data: NotesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NotesConnectionQueryVariables, query: string}> {
        return requester<{data: NotesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NotesConnectionQueryVariables, query: string}, NotesConnectionQueryVariables>(NotesConnectionDocument, variables, options);
      },
    about(variables: AboutQueryVariables, options?: C): Promise<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}> {
        return requester<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}, AboutQueryVariables>(AboutDocument, variables, options);
      },
    aboutConnection(variables?: AboutConnectionQueryVariables, options?: C): Promise<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}> {
        return requester<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}, AboutConnectionQueryVariables>(AboutConnectionDocument, variables, options);
      },
    site_config(variables: Site_ConfigQueryVariables, options?: C): Promise<{data: Site_ConfigQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Site_ConfigQueryVariables, query: string}> {
        return requester<{data: Site_ConfigQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Site_ConfigQueryVariables, query: string}, Site_ConfigQueryVariables>(Site_ConfigDocument, variables, options);
      },
    site_configConnection(variables?: Site_ConfigConnectionQueryVariables, options?: C): Promise<{data: Site_ConfigConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Site_ConfigConnectionQueryVariables, query: string}> {
        return requester<{data: Site_ConfigConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Site_ConfigConnectionQueryVariables, query: string}, Site_ConfigConnectionQueryVariables>(Site_ConfigConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  